// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4escyyLRXrVONHMdn8tj87c-_unpDgE',
    appId: '1:358449484532:web:cda5eca14615416a8d84a1',
    messagingSenderId: '358449484532',
    projectId: 'metro-coffee-staging',
    authDomain: 'metro-coffee-staging.firebaseapp.com',
    storageBucket: 'metro-coffee-staging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_SIAO2wm38rHaDjxE1tg4BUsben24NHc',
    appId: '1:358449484532:android:06626973df5e17a68d84a1',
    messagingSenderId: '358449484532',
    projectId: 'metro-coffee-staging',
    storageBucket: 'metro-coffee-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79UoNWVcLV8hmyY8JXh-RB7fpIi4EPc0',
    appId: '1:358449484532:ios:d82c8733581d3dd68d84a1',
    messagingSenderId: '358449484532',
    projectId: 'metro-coffee-staging',
    storageBucket: 'metro-coffee-staging.appspot.com',
    androidClientId: '358449484532-72e1s9m0i4648tlbrlbgta42trbbuul9.apps.googleusercontent.com',
    iosClientId: '358449484532-n5fuctdaigfnsj3ot1oo4vi79qqnqvdl.apps.googleusercontent.com',
    iosBundleId: 'com.clickandpress.metrocoffee.np.staging',
  );
}
